services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # SECURITY
    #

    Pimcore\Bundle\AdminBundle\EventListener\AdminSecurityListener: ~

    Pimcore\Bundle\AdminBundle\EventListener\CsrfProtectionListener: ~
    #
    # EXCEPTION HANDLING
    #

    Pimcore\Bundle\AdminBundle\EventListener\AdminExceptionListener: ~

    #
    # GRID CONFIG CLEANUP
    #
    Pimcore\Bundle\AdminBundle\EventListener\GridConfigListener: ~

    #
    # IMPORT CONFIG CLEANUP
    #
    Pimcore\Bundle\AdminBundle\EventListener\ImportConfigListener:
        deprecated:
            package: 'pimcore/pimcore'
            version: '10.6'
            message: 'The "%service_id%" service is deprecated and will be removed in Pimcore 11'


    #
    # MISC
    #

    Pimcore\Bundle\AdminBundle\EventListener\AdminSessionBagListener: ~
    Pimcore\Bundle\AdminBundle\EventListener\HttpCacheListener: ~

    Pimcore\Bundle\AdminBundle\EventListener\CustomAdminEntryPointCheckListener:
        arguments: ['%pimcore_admin.custom_admin_path_identifier%']

    Pimcore\Bundle\AdminBundle\EventListener\UserPerspectiveListener:
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: admin }

    Pimcore\Bundle\AdminBundle\EventListener\UsageStatisticsListener:
        calls:
            - [setLogger, [ '@logger' ]]
        tags:
            - { name: monolog.logger, channel: admin_statistics }

    Pimcore\Bundle\AdminBundle\EventListener\EnablePreviewTimeSliderListener: ~

    #
    # Workflows
    #
    Pimcore\Bundle\AdminBundle\EventListener\WorkflowManagementListener:
        public: true # can be disabled
