services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # Notification Services
    #

    Pimcore\Model\Notification\Service\NotificationService:
        public: true

    Pimcore\Model\Notification\Service\UserService: ~

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    Pimcore\Bundle\AdminBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    #
    # TRANSLATIONS
    #

    Pimcore\Bundle\AdminBundle\Translation\AdminUserTranslator: ~

    #
    # GDPR Services
    #

    # Tagged data providers will be injected from compiler pass
    Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Manager: ~

    # Providers implementing DataProviderInterface will be auto-tagged via autoconfiguration
    Pimcore\Bundle\AdminBundle\GDPR\DataProvider\DataObjects:
        arguments:
            $config: '%pimcore.gdpr-data-extrator.dataobjects%'

    Pimcore\Bundle\AdminBundle\GDPR\DataProvider\Assets:
        arguments:
            $config: '%pimcore.gdpr-data-extrator.assets%'

    Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail: ~
    Pimcore\Bundle\AdminBundle\GDPR\DataProvider\PimcoreUsers:
        arguments:
            $logsDir: '%kernel.logs_dir%'


    #
    # Grid Helper Service
    #

    Pimcore\Bundle\AdminBundle\Helper\GridHelperService: ~


    #
    # Default Preview Generator
    #

    Pimcore\Model\DataObject\ClassDefinition\PreviewGeneratorInterface:
        class: Pimcore\Bundle\AdminBundle\Service\PreviewGenerator

    #
    # Twig Extensions
    #

    Pimcore\Twig\Extension\AdminExtension: ~
    
    Pimcore\Bundle\AdminBundle\Twig\Extension\AdminExtension: ~

    #
    # Workflows
    #
    
    Pimcore\Bundle\AdminBundle\Service\Workflow\ActionsButtonService: ~

    #
    # System Config Services
    #
    Pimcore\Bundle\AdminBundle\System\Config: ~
    Pimcore\Bundle\AdminBundle\System\AdminConfig: ~


    #
    # System Config Helper Service
    #
    Pimcore\Bundle\AdminBundle\Helper\SystemConfig: ~
