services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # ENVIRONMENT
    #
    # Predefined core environment implementations. Options will be set from configuration.
    #

    Pimcore\Bundle\EcommerceFrameworkBundle\EnvironmentInterface: '@pimcore_ecommerce.environment'

    Pimcore\Bundle\EcommerceFrameworkBundle\IEnvironment:
        alias: Pimcore\Bundle\EcommerceFrameworkBundle\EnvironmentInterface
        # deprecated: 'The "%alias_id%" is deprecated, use Pimcore\Bundle\EcommerceFrameworkBundle\EnvironmentInterface instead'

    Pimcore\Bundle\EcommerceFrameworkBundle\Environment:
        arguments:
            $options: '%pimcore_ecommerce.environment.options%'

    Pimcore\Bundle\EcommerceFrameworkBundle\SessionEnvironment:
        arguments:
            $options: '%pimcore_ecommerce.environment.options%'
