services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # DOCUMENT TAG HANDLING (EDITABLES)
    #

    Pimcore\Document\Editable\Block\BlockStateStack:
        public: true


    Pimcore\Document\Editable\EditableHandler:
        public: true
        arguments:
            $templating: '@pimcore.templating.engine.delegating'
            $translator: '@Pimcore\Bundle\AdminBundle\Translation\AdminUserTranslator'
            $responseStack: '@Pimcore\Http\ResponseStack'
            $httpKernelRuntime: '@twig.runtime.httpkernel'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: pimcore }


    Pimcore\Document\Editable\EditmodeEditableDefinitionCollector: ~

    #
    # AREABRICKS
    #

    pimcore.area.brick_manager: '@Pimcore\Extension\Document\Areabrick\AreabrickManager'

    # scoped container containing only the registered area bricks
    # will be configured in areabrick pass
    pimcore.document.areabrick.brick_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: false
        tags: ['container.service_locator']


    Pimcore\Extension\Document\Areabrick\AreabrickManager:
        arguments:
            $container: '@pimcore.document.areabrick.brick_locator'

    Pimcore\Extension\Document\Areabrick\AreabrickManagerInterface:
        alias: Pimcore\Extension\Document\Areabrick\AreabrickManager
        public: true

    #
    # DOCUMENT RELATED SERVICES
    #

    # TODO inject user?
    Pimcore\Model\Document\Service:
        public: true

    Symfony\Component\HttpKernel\Fragment\FragmentRendererInterface: '@fragment.renderer.inline'

    Pimcore\Document\Renderer\DocumentRenderer:
        public: true

    Pimcore\Document\Editable\EditableUsageResolver:
        public: true

    Pimcore\Document\DocumentStack:
        public: true
