services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # DOCUMENT TAG HANDLING (EDITABLES)
    #

    # the used naming strategy will be aliased to "pimcore.document.tag.naming.strategy" by the extension based on
    # the pimcore.documents.editables.naming_strategy config value
    Pimcore\Document\Tag\NamingStrategy\NamingStrategyInterface: '@pimcore.document.tag.naming.strategy'

    pimcore.document.tag.naming.strategy.legacy:
        class: Pimcore\Document\Tag\NamingStrategy\LegacyNamingStrategy

    pimcore.document.tag.naming.strategy.nested:
        class: Pimcore\Document\Tag\NamingStrategy\NestedNamingStrategy

    Pimcore\Document\Editable\Block\BlockStateStack:
        public: true

    pimcore.document.tag.block_state_stack:
        alias: Pimcore\Document\Editable\Block\BlockStateStack
        public: true
        deprecated: 'The "%alias_id%" service is deprecated. Use "Pimcore\Document\Editable\Block\BlockStateStack" instead'

    Pimcore\Document\Tag\Block\BlockStateStack:
        alias: Pimcore\Document\Editable\Block\BlockStateStack
        deprecated: 'The "%alias_id%" service is deprecated. Use "Pimcore\Document\Editable\Block\BlockStateStack" instead'

    Pimcore\Document\Editable\EditableHandler:
        public: true
        arguments:
            $templating: '@templating'
            $translator: '@Pimcore\Bundle\AdminBundle\Translation\AdminUserTranslator'
            $responseStack: '@Pimcore\Http\ResponseStack'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: pimcore }

    #
    # AREABRICKS
    #

    pimcore.area.brick_manager: '@Pimcore\Extension\Document\Areabrick\AreabrickManager'

    # scoped container containing only the registered area bricks
    # will be configured in areabrick pass
    pimcore.document.areabrick.brick_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: false
        tags: ['container.service_locator']


    Pimcore\Extension\Document\Areabrick\AreabrickManager:
        arguments:
            $container: '@pimcore.document.areabrick.brick_locator'

    Pimcore\Extension\Document\Areabrick\AreabrickManagerInterface:
        alias: Pimcore\Extension\Document\Areabrick\AreabrickManager
        public: true

    #
    # DOCUMENT RELATED SERVICES
    #

    # TODO inject user?
    Pimcore\Model\Document\Service:
        public: true

    Pimcore\Document\Renderer\DocumentRenderer:
        public: true
        arguments:
            $fragmentRenderer: '@fragment.renderer.inline'

    Pimcore\Document\Editable\EditableUsageResolver:
        public: true

    Pimcore\Document\Tag\TagUsageResolver:
        alias: Pimcore\Document\Editable\EditableUsageResolver
        public: true
        deprecated: 'The "%alias_id%" service is deprecated. Use "Pimcore\Document\Editable\EditableUsageResolver" instead'

    Pimcore\Document\DocumentStack:
        public: true

    #
    # DOCUMENT TAG MIGRATION
    #

    pimcore.document.tag.naming.migration.strategy.analyze:
        class: Pimcore\Document\Tag\NamingStrategy\Migration\AnalyzeMigrationStrategy
        arguments:
            $db: '@database_connection'

    pimcore.document.tag.naming.migration.strategy.render:
        class: Pimcore\Document\Tag\NamingStrategy\Migration\RenderMigrationStrategy
