services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # IMPLEMENTATION FACTORIES
    #
    # Class maps and prefixes will be set from the extension as they are loaded from config
    #

    # document editable loader
    Pimcore\Model\Document\Editable\Loader\EditableLoader:
        public: true

    pimcore.implementation_loader.document.tag:
        alias: Pimcore\Model\Document\Editable\Loader\EditableLoader
        public: true
        deprecated: 'The "%alias_id%" service is deprecated. Use "Pimcore\Model\Document\Editable\Loader\EditableLoader" instead'

    # object data loader
    pimcore.implementation_loader.object.data:
        class: Pimcore\Model\DataObject\ClassDefinition\Loader\DataLoader
        public: true

    # asset metadata data loader
    pimcore.implementation_loader.asset.metadata.data:
        class: Pimcore\Model\Asset\Metadata\Loader\DataLoader
        public: true

    # object layout loader
    pimcore.implementation_loader.object.layout:
        class: Pimcore\Model\DataObject\ClassDefinition\Loader\LayoutLoader
        public: true

    # model factory
    Pimcore\Model\FactoryInterface: '@Pimcore\Model\Factory'
    Pimcore\Model\Factory:
        calls:
            - [addLoader, ['@Pimcore\Model\Factory\FallbackBuilder']]

    # public alias which is used throughout code base
    # TODO replace with FQCN reference in wherever this is used
    pimcore.model.factory:
        alias: Pimcore\Model\Factory
        public: true

    # fallback model builder for pimcore model factory
    Pimcore\Model\Factory\FallbackBuilder:
        public: false
