services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # Example custom templating helper
    # app.templating.helper.foobar:
    #    class: AppBundle\Templating\Helper\Example
    #    tags:
    #        - { name: templating.helper, alias: fooBar }

    # Example event listener for objects
    # app.event_listener.test:
    #    class: AppBundle\EventListener\TestListener
    #    tags:
    #        - { name: kernel.event_listener, event: pimcore.object.preUpdate, method: onObjectPreUpdate }
