pimcore_generic_execution_engine:
    error_handling: 'continue_on_error'
    execution_context:
        default:
            translations_domain: admin
            error_handling: 'continue_on_error'