services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # INSTALLER
    #
    Pimcore\Bundle\PersonalizationBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcorePersonalizationBundle')"

    # auto-register all controllers as services
    Pimcore\Bundle\PersonalizationBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    # Newsletter Adapter
    pimcore.document.newsletter.factory.default:
        class: Pimcore\Document\Newsletter\DefaultAddressSourceAdapterFactory
        arguments:
            - 'Pimcore\Bundle\PersonalizationBundle\Document\Newsletter\AddressSourceAdapter\DefaultAdapter'