services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # SECURITY
    #

    # standard user provider returning admin users wrapped in a Pimcore\Bundle\AdminBundle\Security\User\User proxy object.
    # using this user provider allows implementations to authenticate against pimcore users on every desired firewall
    Pimcore\Bundle\AdminBundle\Security\User\UserProvider:
        deprecated:
            package: 'pimcore/pimcore'
            version: '10.6'
            message: 'The "%service_id%" service is deprecated and will be removed in Pimcore 11. Use \Pimcore\Security\User\TokenStorageUserResolver instead.'

    # the password encoder factory builds a dedicated encoder per user
    # as we need the user instance to encode passwords. see pimcore.security.encoder_factories
    # we don't specifiy this as fully qualified class name as there can be multiple factories (one for each user type)
    pimcore_admin.security.password_encoder_factory:
        class: Pimcore\Security\Encoder\Factory\UserAwareEncoderFactory
        arguments:
            - Pimcore\Bundle\AdminBundle\Security\Encoder\AdminPasswordEncoder


    # the password hasher factory builds a dedicated hasher per user
    # as we need the user instance to hash passwords.
    # we don't specifiy this as fully qualified class name as there can be multiple factories (one for each user type)
    pimcore_admin.security.password_hasher_factory:
        class: Pimcore\Security\Hasher\Factory\UserAwarePasswordHasherFactory
        arguments:
            - Pimcore\Bundle\AdminBundle\Security\Hasher\AdminPasswordHasher

    # Authenticators for handling admin login and session authentications
    Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminLoginAuthenticator:
        public: false
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminTokenAuthenticator:
        public: false
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminSessionAuthenticator:
        public: false
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    pimcore.security.authenticator.admin_pre_auth:
        class: Pimcore\Bundle\AdminBundle\Security\Authenticator\PreAuthenticatedAdminSessionAuthenticator
        public: false
        abstract: true
        calls:
            - [ setLogger, [ '@logger' ] ]
        arguments:
            $userProvider: !abstract defined by the factory
            $tokenStorage: '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'
            $firewallName: !abstract defined by the factory


    Pimcore\Bundle\AdminBundle\Security\Event\LogoutListener: ~

    Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver:
        public: true
        arguments:
            - '@security.token_storage'
        deprecated:
            package: 'pimcore/pimcore'
            version: '10.6'
            message: 'The "%service_id%" service is deprecated and will be removed in Pimcore 11. Use \Pimcore\Security\User\TokenStorageUserResolver instead.'

    Pimcore\Bundle\AdminBundle\Security\User\UserLoader:
        deprecated:
            package: 'pimcore/pimcore'
            version: '10.6'
            message: 'The "%service_id%" service is deprecated and will be removed in Pimcore 11. Use \Pimcore\Security\User\UserLoader instead.'


    Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler:
        public: true
        arguments:
            - '%pimcore_admin.csrf_protection.excluded_routes%'
            - '@twig'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: security }

    Pimcore\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler:
        public: true
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    Pimcore\Bundle\AdminBundle\Security\User\UserChecker:
        deprecated:
            package: 'pimcore/pimcore'
            version: '10.6'
            message: 'The "%service_id%" alias is deprecated and will be removed in Pimcore 11. Use Pimcore\Security\User\UserChecker instead.'
