services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # COMMANDS
    #

    # auto-register all commands as services
    Pimcore\Bundle\CoreBundle\Command\:
        resource: '../src/Command'
        exclude: '../src/Command/Bundle/Helper'
        tags: ['console.command']

    Pimcore\Bundle\CoreBundle\Command\Bundle\Helper\PostStateChange:
        arguments:
            - '@Pimcore\Cache\Symfony\CacheClearer'
            - '@Pimcore\Tool\AssetsInstaller'
            - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'

    Pimcore\Bundle\CoreBundle\Command\OptimizeImageThumbnailsCommand:
        arguments:
            - '@Pimcore\Image\Optimizer'
        tags:
            - { name: console.command, command: 'pimcore:thumbnails:optimize-images' }

    Pimcore\Bundle\CoreBundle\Command\MaintenanceCommand:
        arguments:
            - '@Pimcore\Maintenance\Executor'
            - '@logger'
        tags:
            - { name: console.command, command: 'pimcore:maintenance' }
            - { name: console.command, command: 'maintenance' }

    Pimcore\Bundle\CoreBundle\Command\Bundle\InstallCommand:
        arguments:
            - '@Pimcore\Extension\Bundle\PimcoreBundleManager'
            - '@Pimcore\Bundle\CoreBundle\Command\Bundle\Helper\PostStateChange'
        tags:
            - { name: console.command, command: 'pimcore:bundle:install' }

    Pimcore\Bundle\CoreBundle\Command\Bundle\UninstallCommand:
        arguments:
            - '@Pimcore\Extension\Bundle\PimcoreBundleManager'
            - '@Pimcore\Bundle\CoreBundle\Command\Bundle\Helper\PostStateChange'
        tags:
            - { name: console.command, command: 'pimcore:bundle:uninstall' }

    Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand:
        calls:
            - [setClassDefinitionManager, ['@Pimcore\Model\DataObject\ClassDefinition\ClassDefinitionManager']]
        tags:
            - { name: console.command, command: 'pimcore:deployment:classes-rebuild' }

    Pimcore\Bundle\CoreBundle\Command\Migrate\StorageCommand:
        arguments:
            $locator: !tagged_locator { tag: flysystem.storage }
