_pimcore_service_robots_txt:
    path: /robots.txt
    defaults: { _controller: Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::robotsTxtAction }

_pimcore_service_common_files:
    path: /{filename}
    defaults: { _controller: Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::commonFilesAction }
    requirements:
        filename: '(robots\.txt|crossdomain\.xml|favicon\.ico|browserconfig\.xml|wpad\.dat|\.crl)'

_pimcore_service_common_files_apple_touch_icon:
    path: /{filename}
    defaults: { _controller: Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::commonFilesAction }
    requirements:
        filename: 'apple\-touch\-icon.*'

_pimcore_service_thumbnail:
    path: '{prefix}{type}-thumb__{assetId}__{thumbnailName}/{filename}'
    defaults: { _controller: Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::thumbnailAction}
    requirements:
        prefix: '.*'
        type: 'video|image'
        assetId: '\d+'
        thumbnailName: '[a-zA-Z0-9_\-]+'
        filename: '.*'

_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

# auto loads routes from all bundles in config/pimcore/routing.yaml
_pimcore_bundle_auto:
    resource: .
    type: pimcore_bundle

pimcore_webdav:
    path: /asset/webdav{path}
    defaults: { _controller: Pimcore\Bundle\CoreBundle\Controller\WebDavController::webdavAction }
    requirements:
        path: '.*'
