# Pimcore
pimcore_admin:

    session:
        attribute_bags:
            - pimcore_admin
            - pimcore_objects
            - pimcore_copy
            - pimcore_gridconfig
            - pimcore_importconfig

    # the following routes won't be double checked for authentication
    # this usually applies to login routes
    unauthenticated_routes:
        - { route: pimcore_settings_display_custom_logo }
        - { route: pimcore_admin_login }
        - { route: pimcore_admin_webdav }

    translations:
        path: "@PimcoreCoreBundle/translations"

    user:
        default_key_bindings:
            save:
                key: 'S'
                action: save
                ctrl: true
            publish:
                key: 'P'
                action: publish
                ctrl: true
                shift: true
            unpublish:
                key: 'U'
                action: unpublish
                ctrl: true
                shift: true
            rename:
                key: 'R'
                action: rename
                alt: true
                shift: true
            refresh:
                key: 't'
                action: refresh
            open_asset:
                key: 'A'
                action: openAsset
                ctrl: true
                shift: true
            open_object:
                key: 'O'
                action: openObject
                ctrl: true
                shift: true
            open_document:
                key: 'D'
                action: openDocument
                ctrl: true
                shift: true
            open_class_editor:
                key: 'C'
                action: openClassEditor
                ctrl: true
                shift: true
            open_in_tree:
                key: 'L'
                action: openInTree
                ctrl: true
                shift: true
            show_meta_info:
                key: 'I'
                action: showMetaInfo
                alt: true
            search_document:
                key: 'W'
                action: searchDocument
                alt: true
            search_asset:
                key: 'A'
                action: searchAsset
                alt: true
            search_object:
                key: 'O'
                action: searchObject
                alt: true
            show_element_history:
                key: 'H'
                action: showElementHistory
                alt: true
            close_all_tabs:
                key: 'T'
                action: closeAllTabs
                alt: true
            search_and_replace_assignments:
                key: 'S'
                action: searchAndReplaceAssignments
                alt: true
            redirects:
                key: 'R'
                action: redirects
                ctrl: false
                alt: true
            shared_translations:
                key: 'T'
                action: sharedTranslations
                ctrl: true
                alt: true
            recycle_bin:
                key: 'R'
                action: recycleBin
                ctrl: true
                alt: true
            notes_events:
                key: 'N'
                action: notesEvents
                ctrl: true
                alt: true
            tag_manager:
                key: 'H'
                action: tagManager
                ctrl: true
                alt: true
            tag_configuration:
                key: 'N'
                action: tagConfiguration
                ctrl: true
                alt: true
            users:
                key: 'U'
                action: users
                ctrl: true
                alt: true
            roles:
                key: 'P'
                action: roles
                ctrl: true
                alt: true
            clear_all_caches:
                key: 'Q'
                action: clearAllCaches
                ctrl: false
                alt: true
            clear_data_cache:
                key: 'C'
                action: clearDataCache
                ctrl: false
                alt: true

# adds support for admin related routes that will be used to determine the request context in PimcoreContextGuesser
pimcore:
    web_profiler:
        toolbar:
            excluded_routes:
                - { path: '^/admin/asset/image-editor' }
    context:
        admin:
            routes:
                - { path: ^/admin(/.*)?$ }
                - { route: ^pimcore_admin_ }
    security:
        password_hasher_factories:
            Pimcore\Bundle\AdminBundle\Security\User\User: pimcore_admin.security.password_hasher_factory


flysystem:
    storages:
        pimcore.admin.storage:
            # Storage for shared admin resources, such as the user avatar, custom logos, ...
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/admin'

twig:
    globals:
        pimcore_csrf: '@Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler'
        pimcore_csp: '@Pimcore\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler'

monolog:
    handlers:
        usage:
            type: stream
            path:  "%kernel.logs_dir%/usage.log"
            level: debug
            channels: ['admin_statistics']