scheb_two_factor:
    two_factor_condition: Pimcore\Bundle\AdminBundle\Security\PimcoreUserTwoFactorCondition
    google:
        enabled: true                                       # If Google Authenticator should be enabled, default false
        server_name: Pimcore                                # Server name used in QR code
        issuer: Pimcore 2 Factor Authentication             # Issuer name used in QR code

    security_tokens:
        - Pimcore\Bundle\AdminBundle\Security\Authentication\Token\TwoFactorRequiredToken
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\AdminBundle\Security\PimcoreUserTwoFactorCondition: ~
