
name: "PHP-CS-Fixer"

on:
    push:
        branches:
            - "6.9"

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:latest

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply php-cs-fixer changes