
name: "PR Checklist"

on:
    pull_request:
        types: [opened]

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              env:
                  MESSAGE: |
                      ### Quality Assurance Checklist (to be used by Pimconauts üßë‚ÄçüöÄ) .
                      
                      - [ ] Target branch (`10.4` for bug fixes, others `10.x`)
                      - [ ] Tests (if it's testable code, there should be a test for it - [get help](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Core_Tests.html))
                      - [ ] Docs (every functionality needs to be documented, [see here](https://github.com/pimcore/pimcore/tree/10.x/doc)) 
                      - [ ] Migration incl. `install.sql` (e.g. if the database schema changes, ...) 
                      - [ ] Upgrade notes (deprecations, important information, migration hints, ...) 
                      - [ ] Label
                      - [ ] Milestone
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: ${MESSAGE}
                      })
                      
