
name: "PR Checklist"

on:
    pull_request_target:
        types: [opened]

permissions:
    pull-requests: write

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
              env:
                  MESSAGE: |
                      ### Review Checklist
                      - [ ] Target branch (`10.5` for bug fixes, others `11.x`)
                      - [ ] Bug fix: check if files are affected that were [moved to a bundle](https://github.com/pimcore/pimcore/issues/12094) - create a PR there if applicable
                      - [ ] Tests (if it's testable code, there should be a test for it - [get help](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Testing/Core_Tests.html))
                      - [ ] Docs (every functionality needs to be documented, [see here](https://github.com/pimcore/pimcore/tree/11.x/doc)) 
                      - [ ] [Migration](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Migrations.html) incl. `install.sql` (e.g. if the database schema changes, ...) 
                      - [ ] Upgrade notes (deprecations, important information, migration hints, ...) 
                      - [ ] Label
                      - [ ] Milestone
              with:
                  script: |
                      const { MESSAGE } = process.env
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `${MESSAGE}`
                      })
                      
