framework:
    messenger:
        routing:
            'Pimcore\Bundle\WebToPrintBundle\Messenger\GenerateWeb2PrintPdfMessage': pimcore_core
pimcore:
    documents:
        type_definitions:
            map:
                printpage:
                    class: Pimcore\Bundle\WebToPrintBundle\Model\Document\Printpage
                    children_supported: false
                    direct_route: true
                    predefined_document_types: true
                printcontainer:
                    class: Pimcore\Bundle\WebToPrintBundle\Model\Document\Printcontainer
                    only_printable_childrens: true
                    direct_route: true
                    predefined_document_types: true